### ISSUE TITLE
Dialogue Manager 3.10 compile error in Godot 4.6's exported build.

### ISSUE THREAD

**Issue by Irrawa** [nathanhoad/godot_dialogue_manager#1098]
**Describe the bug**
Export the project with dialogue manager is fine. But during launching the exported .exe file, error happens:

```
Godot Engine v4.6.stable.official.89cea1439 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 580.92 - Compatibility - Using Device: NVIDIA - NVIDIA RTX 4000 Ada Generation Laptop GPU

SCRIPT ERROR: Parse Error: Could not resolve class "DMPlugin", because of a parser error.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:32)
SCRIPT ERROR: Parse Error: Could not find type "EditorFileSystem" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:64)
SCRIPT ERROR: Parse Error: Identifier "EditorInterface" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:64)
SCRIPT ERROR: Parse Error: Identifier "EditorInterface" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:71)
SCRIPT ERROR: Parse Error: Could not find type "EditorFileSystem" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:80)
SCRIPT ERROR: Parse Error: Identifier "EditorInterface" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/utilities/dialogue_cache.gd:80)
SCRIPT ERROR: Compile Error: Failed to compile depended scripts.
          at: GDScript::reload (res://addons/dialogue_manager/compiler/compilation.gd:0)
SCRIPT ERROR: Compile Error: Failed to compile depended scripts.
          at: GDScript::reload (res://addons/dialogue_manager/compiler/compiler.gd:0)
SCRIPT ERROR: Compile Error: Failed to compile depended scripts.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:0)
ERROR: Failed to load script "res://addons/dialogue_manager/dialogue_manager.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2907)
```

Things work fine in the editor's Run Project. Failure happens only in exported projects.

**Affected version**

- Dialogue Manager version: 3.10
- Godot version:  v4.6.stable.official.89cea1439

**To Reproduce**

Export a project with dialogue manager 3.10 installed. Then run the .console.exe file, you can see the error messages.

**Expected behavior**
Plugin should work fine in an exported project.

**FYI**
It works fine in version 3.9.0. This bug happens after I upgrading from 3.9.0 to 3.10.0.
